import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { CopilotKit } from "@copilotkit/react-core";
import "@copilotkit/react-ui/styles.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <CopilotKit publicApiKey={process.env.NEXT_PUBLIC_COPILOT_API_KEY}>
            <header className="p-4 bg-gray-100">
              <SignedOut><SignInButton /></SignedOut>
              <SignedIn><UserButton /></SignedIn>
            </header>
            <main className="container mx-auto p-4">{children}</main>
          </CopilotKit>
        </ClerkProvider>
      </body>
    </html>
  );
}
